### ISSUE TITLE
Pre Req

### ISSUE THREAD

**Issue by RachBLondon** [FAC6/FAC7#2]
Matt and Rachel

Pre req
- more emphasis on javascript DOM manipulation 
- article and tasks on function (maybe eloquent javascript)
- shorter pre reques (might encourage more female applications - i.e. research shows women will worry about a job description if they only know 90%, but men will apply if they meet 60%)
- html & CSS essential
- remove Jquery
- make a website (index.html & CSS site) — good
- indication of priority on prerequisite
- look for good quality html, css & javascript free online.

**Comment by nelsonic** [comment]
@RachBLondon This was a very good observation. (point 3) did it find a new home?
